# Generated by Django 3.0.7 on 2020-10-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/')),
                ('desc', models.CharField(max_length=100)),
                ('rate', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
