# Generated by Django 3.0.7 on 2020-10-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books_data',
            name='img',
            field=models.ImageField(upload_to='media'),
        ),
    ]
