# Generated by Django 3.0.7 on 2020-10-03 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Books_App', '0002_auto_20201001_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='books_data',
            name='Contact',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books_data',
            name='owner',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books_data',
            name='title',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='books_data',
            name='desc',
            field=models.CharField(max_length=200),
        ),
    ]
