# Generated by Django 3.0.7 on 2020-10-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books_App', '0003_auto_20201003_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books_data',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='books_data',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
