# Generated by Django 3.0.7 on 2020-10-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books_App', '0004_auto_20201003_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='books_data',
            name='type',
            field=models.CharField(choices=[('Islamic', 'Islamic'), ('Nineth_Class', 'Nineth_Class'), ('Tenth_Class', 'Tenth_Class'), ('Eleven_Class', 'Eleven_Class')], default='Islamic', max_length=20),
        ),
    ]
