# Generated by Django 3.0.7 on 2020-10-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books_App', '0005_books_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books_data',
            name='type',
            field=models.CharField(choices=[('Islamic', 'Islamic'), ('Novel', 'Novel'), ('Nineth_Class', 'Nineth_Class'), ('Tenth_Class', 'Tenth_Class'), ('Eleven_Class', 'Eleven_Class'), ('Twelth_Class', 'Twelth_Class')], default='Islamic', max_length=20),
        ),
    ]
