# Generated by Django 3.0.7 on 2020-10-04 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books_App', '0006_auto_20201004_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books_data',
            old_name='type',
            new_name='cat_type',
        ),
    ]
