# Generated by Django 3.0.7 on 2020-10-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books_App', '0007_auto_20201004_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books_data',
            name='cat_type',
            field=models.CharField(choices=[('Islamic', 'Islamic'), ('Novel', 'Novel'), ('Nineth_Class', 'Nineth_Class'), ('Tenth_Class', 'Tenth_Class'), ('Eleven_Class', 'Eleven_Class'), ('Twelth_Class', 'Twelth_Class'), ('Common', 'Common')], default='Common', max_length=20),
        ),
    ]
